account/urls.py
from django.urls import path
from account import views

urlpatterns = [
	path('login/', views.user_login, name='login_page'),
	path('register/', views.user_register, name='register_page'),
	path('logout/', views.user_logout, name='logout_page'),
]

lab_trading/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('', include('exchange.urls')),
    path('trading/', include('trading_platform.urls')),
    path('manage/', include('manage_admin.urls')),

]

trading_platform/urls.py
from django.urls import path
from trading_platform import views

urlpatterns = [
	path('<int:trading_screen_id>/dashboard/', views.user_dashboard, name='user_dashboard'),
	
	path('<int:trading_screen_id>/cancel-all/', views.cancel_all_orders, name='cancel_all_orders'),
	path('<int:trading_screen_id>/sync-amounts/', views.sync_amounts, name='sync_amounts'),

    path('updateOrder/', views.update_order, name='update_order'),
    path('cancelOrder/<int:order_id>', views.cancel_order, name='cancel_order'),
    
	path('<int:trading_screen_id>/<str:currency_1_symbol>/<str:currency_2_symbol>/order/', views.create_order, name='create_order'),
	path('<int:trading_screen_id>/<str:currency_1_symbol>/<str:currency_2_symbol>', views.trading_dashboard, name='trading_dashboard'),

]

account/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _
from django.db import models
import pytz
from datetime import datetime, date, timedelta
from exchange.models import *

from account.manager import UserManager


orders_types = ["market", "limit", "stop-loss", "take-profit",
                "stop-loss-limit", "take-profit-limit", "settle-position"]


class NotEnoughBalance(Exception):
    pass

# Create your models here.


class User(AbstractUser):

    """
    User object
    Represents a person
    """

    username = None

    email = models.EmailField(_('email address'), unique=True)

    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    # Spoken language (FR/NL)
    language_code = models.CharField(max_length=5, default="fr")

    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    phone_numer = models.CharField(max_length=15)
    street = models.CharField(max_length=255)
    number = models.CharField(max_length=255)
    box = models.CharField(max_length=255)
    city = models.CharField(max_length=255)
    zip_code = models.CharField(max_length=32, default='')
    country_code = models.CharField(max_length=32, default='')

    # Overriding of the base django user
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()

    @property
    def serialized(self):
        return {
            'email': self.email,
            'language_code': self.language_code
        }

    def __str__(self):
        return self.email


class TradingScreen(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             null=True, blank=True, related_name="trading_screens")
    allowed_pairs = models.ManyToManyField(Pair)
    exchange_api = models.ForeignKey(ExchangeApi, on_delete=models.CASCADE)
    enabled = models.BooleanField(default=True)

    def __str__(self):
        return '{} {}'.format(self.id, self.user)

    def cancel_all_orders(self):
        trading_api = self.exchange_api.get_class()

        for order in Order.objects.filter(trading_screen=self):
            trading_api.cancel_order(order)

        trading_api.cancel_all_orders(Order.objects.filter(trading_screen=self))

    def sync_currency_amounts(self):
        trading_api = self.exchange_api.get_class()
        currencies_amounts = trading_api.get_currencies_amounts()

        for symbol, balance in currencies_amounts.items():

            # Create a currency amount

            try:

                currency = Currency.objects.filter(
                    exchange=self.exchange_api.exchange).get(symbol=symbol)

                currency_amount = CurrencyAmount.objects.create(
                    currency=currency, trading_screen=self, amount=balance)

                print(currency_amount)

            except Exception as e:
                print('\n\n----------------------->', symbol, balance, e)

    def create_order(self, order_type, pair, volume, entry_price, take_profit, stop_loss, currency_1_value, currency_2_value):
        api_response = False
        trading_api = self.exchange_api.get_class()

        # Getting Pair
        pair = Pair.objects.filter(currency_1=currency_1_value.currency).get(
            currency_2=currency_2_value.currency)

        order_obj = Order()

        order_obj.order_type = order_type
        order_obj.pair = pair
        order_obj.volume = volume
        order_obj.entry_price = entry_price
        order_obj.take_profit = take_profit
        order_obj.stop_loss = stop_loss

        order_obj.trading_screen = self

        order_obj.last_balance = CurrencyAmount.objects.filter(trading_screen=self).filter(
            currency=pair.currency_1).last()

        order_obj.save()

        self.sync_currency_amounts()

    def get_pair_price_history(self, pair, date_from, date_to, total_intervals):

        ret_list = []

        # Calculate dates
        time_between = (date_to - date_from) / total_intervals

        for i in range(0, total_intervals + 1):

            date_at = date_from + (time_between * i)

            # Find pair value at that time
            pair_value = PairValue.objects.filter(pair=pair).filter(
                created_on__lte=date_at).order_by('id').last()

            pair_price = pair_value.value if pair_value else 0

            currency_1_amount = CurrencyAmount.objects.filter(trading_screen=self).filter(currency=pair.currency_1).filter(
                created_on__lte=date_at).order_by('id').last()

            currency_2_amount = CurrencyAmount.objects.filter(trading_screen=self).filter(currency=pair.currency_2).filter(
                created_on__lte=date_at).order_by('id').last()
            currency_1_amount_amount = currency_1_amount.amount if currency_1_amount else 0
            currency_1_amount_price = currency_1_amount_amount * pair_price

            ret_list.append(
                {
                    'time': date_at,
                    'pair_price': pair_price,
                    'currency_1_amount': currency_1_amount_amount,
                    'currency_1_amount_price': currency_1_amount_price,
                    'currency_2_amount': currency_2_amount.amount if currency_2_amount else 0
                }
            )

        return ret_list

    def get_currency_amount_history(self, currency, date_from, date_to, total_intervals):
        ret_list = []

        # Calculate dates
        time_between = (date_to - date_from) / total_intervals

        for i in range(0, total_intervals + 1):

            date_at = date_from + (time_between * i)
            currency_amount = CurrencyAmount.objects.filter(trading_screen=self).filter(currency=currency).filter(
                created_on__lte=date_at).order_by('id').last()

            ret_list.append(
                {
                    'time': date_at,
                    'currency_amount': currency_amount.amount if currency_amount else 0
                }
            )
        return ret_list

    def get_portfolio_evolution(self, cryptos, fiat, date_from=datetime.min, date_to=datetime.now()):

        # Passing naive date_from and date_to to aware
        date_from = date_from.replace(tzinfo=pytz.UTC)
        date_to = date_to.replace(tzinfo=pytz.UTC)

        # Getting the first currency_amount of this trading screen to avoid having a date_from that dates before the death of Jesus Christ
        first_currency_amount = CurrencyAmount.objects.filter(
            trading_screen=self).first()
        if first_currency_amount and first_currency_amount.created_on > date_from:
            date_from = first_currency_amount.created_on

        # Getting the first pair_value ever to be sure to have a value over 0
        first_pair_value = PairValue.objects.first()
        if first_pair_value and first_pair_value.created_on > date_from:
            date_from = first_pair_value.created_on

        # Finding pairs
        pairs = self.allowed_pairs.filter(
            currency_1__in=cryptos).filter(currency_2=fiat)

        first_amount = 0
        last_amount = 0

        # Getting fiat value of cryptos
        for pair in pairs:
            pair_history = self.get_pair_price_history(
                pair, date_from, date_to, 1)
            first_amount += pair_history[0]['currency_1_amount_price']
            last_amount += pair_history[1]['currency_1_amount_price']

        fiat_amount_history = self.get_currency_amount_history(
            fiat, date_from, date_to, 1)
        first_amount += fiat_amount_history[0]['currency_amount']
        last_amount += fiat_amount_history[1]['currency_amount']

        return (first_amount, last_amount)

    def new_currency_pair_values(self, pair):
        new_user_currency_1_amount = CurrencyAmount.objects.create(
            currency=pair.currency_1, trading_screen=self)
        new_user_currency_2_amount = CurrencyAmount.objects.create(
            currency=pair.currency_2, trading_screen=self)

        return (new_user_currency_1_amount, new_user_currency_2_amount)
        start_amount += pair_portfolio_history[0]['currency_1_amount_price']


class CurrencyAmount(models.Model):

    currency = models.ForeignKey(Currency, on_delete=models.CASCADE)
    amount = models.FloatField(default=0)
    created_on = models.DateTimeField(default=datetime.now, blank=True)
    trading_screen = models.ForeignKey(
        TradingScreen, null=True, on_delete=models.CASCADE, related_name="currency_amounts")

    def get_value(self, currency_2_symbol):
        if self.currency.symbol == currency_2_symbol:
            return self.amount
        return self.amount * self.currency.get_market_value(currency_2_symbol)

    def __str__(self):
        return '{} -- {} {} : {}'.format(self.created_on, self.trading_screen, self.currency, self.amount)


class Order(models.Model):

    ORDERS_CHOICES = (
        ('SHORT', 'Short Selling'),
        ('LONG', 'Buy Long')
    )

    order_type = models.CharField(
        max_length=10, choices=ORDERS_CHOICES, default='LONG')
    pair = models.ForeignKey(Pair, on_delete=models.CASCADE)

    volume = models.FloatField(default=0)
    entry_price = models.FloatField(null=True, blank=True)
    take_profit = models.FloatField(null=True, blank=True)
    stop_loss = models.FloatField(null=True, blank=True)
    leverage = models.IntegerField(default=2)

    fees = models.FloatField(default=0)

    trading_screen = models.ForeignKey(TradingScreen, on_delete=models.CASCADE)

    created_on = models.DateTimeField(auto_now_add=True)

    success = models.BooleanField(default=False)

    # OHLC triggers
    # If entry price has been reached, that means that the order has become a position
    position_opened_at = models.DateTimeField(blank=True, null=True)

trading_platform/templates/trader_dashboard.html
{% extends 'layouts/base.html' %} {% load static %}{% load jsonify %} 
{% block head %} {% endblock head %} {% block body %}

<div class="row">
  <div class="col-12 p-2">
    <div class="card p-2 text-center">
      <h1>Shortcuts</h1>
      <div class="d-flex justify-content-between flex-wrap">
        <a href="{% url 'cancel_all_orders' trading_screen.id %}" class="btn btn-danger">Cancel all orders</a>
        <a href="{% url 'sync_amounts' trading_screen.id %}" class="btn btn-primary">Sync portfolio</a>
      </div>
    </div>
  </div>
</div>

<div class="row mt-4">
  <div class="col-md-4 p-2">
    <div class="card p-2 text-center">
      <h1>Total portfolio value in USD</h1>
      <h2>{{ portfolio_usd_value }} $</h2>
    </div>
  </div>
  <div class="col-md-4 p-2">
    <div class="card p2 text-center">
      <h1>Daily portfolio results</h1>
      <h2><h2 style="color: {{daily_portfolio_color}}">{% if daily_portfolio_evolve > 0%}+{% endif %}{{daily_portfolio_evolve}}%</h2></h2>
      <div class="text-left">Was {{daily_portfolio_first_value}}</div>
    </div>
  </div>
  <div class="col-md-4 p-2">
    <div class="card p2 text-center">
      <h1>All time portfolio results</h1>
      <h2><h2 style="color: {{all_time_portfolio_color}}">{% if all_time_portfolio_evolve > 0%}+{% endif %}{{all_time_portfolio_evolve}}%</h2></h2>
      <div class="text-left">Was {{all_time_portfolio_first_value}}</div>
    </div>
  </div>
</div>
<div class="row mt-4">
  <div class="card p-1 col-12">
    <canvas id="myChart" width="800" height="400"></canvas>
  </div>
</div>
<div class="row mt-4">
  {% for pair in pairs %}
  <div class="col-md-3 p-2">
    <div class="card p-2">
      <h3>{{pair.currency_1.name}}</h3>
      <h4>1 {{pair.currency_1.symbol}} is {{pair.value}} $</h4>
      <h4>{{pair.customer_owned_in_dollars}} $  in portfolio</h4>
    <a class="btn btn-primary"
      href="{% url 'trading_dashboard' trading_screen.id pair.currency_1.symbol pair.currency_2.symbol %}"
      >Open trading screen</a
    >
    </div>
  </div>
  {% endfor %}
</div>
{% endblock body %} {% block javascript %}
<script>
  const ctx = document.getElementById("myChart");

  const labels = {{ labels|jsonify }};
  const data = {
    labels: labels,
    datasets: {{ datasets|jsonify}},
  };

  const config = {
    type: "line",
    data: data,
    options: {
      plugins: {
        title: {
          display: true,
          text: "Portfolio evolution (last 24 hours every 30 minutes)",
        },
      },
      responsive: true,
      scales: {
        x: {
          stacked: true,
        },
        y: {
          stacked: true,
        },
      },
    },
  };

  const myChart = new Chart(ctx, config);
</script>
{% endblock javascript %}

trading_platform/templates/trading_screen.html
{% extends 'layouts/base.html' %} {% load static %} {% load django_tables2 %} 
{% block head %} {% endblock head %} {% block body %}
<div class="row mt-4">
  <div class="col-md-8 p-2" style="height: 70vh">
    <!-- TradingView Widget BEGIN -->
    <div id="tradingview_11380" style="height: 100%"></div>

    <script
      type="text/javascript"
      src="https://s3.tradingview.com/tv.js"
    ></script>
    <script type="text/javascript">
      const tradingView = new TradingView.widget({
        autosize: true,
        symbol: "KRAKEN:{{pair_symbol}}",
        interval: "D",
        timezone: "Etc/UTC",
        theme: "light",
        style: "1",
        locale: "fr",
        toolbar_bg: "#f1f3f6",
        enable_publishing: false,
        allow_symbol_change: true,
        container_id: "tradingview_11380",
      });
    </script>
    <!-- TradingView Widget END -->
  </div>
  {% comment %}
  <!-- <div class="col p-2">
            <div class="card">
                <h2>You own {{amount_1.amount}} {{amount_1.currency}}</h2>
                <h2>You own {{amount_2.amount}} {{amount_2.currency}}</h2>
            </div>
        
            <div class="card mt-2">
                <h1>Create a market order</h1>
                <h2>Buy {{amount_1.currency }}</h2>
                <form method="POST" action="{% url 'standard_order' trading_screen.id currency_1.symbol currency_2.symbol%}">
                    {% csrf_token %}
                    <input type="number" step="any" required="true" name="amount" placeholder="amount in {{amount_1.currency}}" />
                    <input type="number" step="any" name="limit" placeholder="limit price in {{amount_1.currency}}" />
                    <input type="submit">
                </form>
                <h2>Sell {{amount_1.currency }}</h2>
                <form method="POST" action="{% url 'standard_order' trading_screen.id currency_1.symbol currency_2.symbol 'sell' %}">
                    {% csrf_token %}
                    <input type="number" step="any" required="true" name="amount" placeholder="amount in {{amount_1.currency}}" />
                    <input type="number" step="any" name="limit" placeholder="limit price in {{amount_1.currency}}" />
                    <input type="submit">
                </form>
            </div>  
        
        </div> -->
  {% endcomment %}

  <div class="col p-2">
    <h3>Your portfolio</h3>
    <div class="card p-2 mb-3 mt-2">
      <h4>{{amount_1.currency.symbol}} : {{amount_1.amount}}</h4>
      <h4>{{amount_2.currency.symbol}} : {{amount_2.amount}}</h4>
    </div>
    <h3>Create an order</h3>
    <div class="card mt-2 p-2 mb-3">
      <form
        method="POST"
        action="{% url 'create_order' trading_screen.id currency_1.symbol currency_2.symbol%}"
      >
        {% csrf_token %}

        <div class="form-check form-check-inline d-flex justify-content-around">
          <label class="me-2"
            ><input
              class="me-2"
              type="radio"
              name="order_type"
              checked
              value="long"
            />Long</label
          >
          <label class="me-2"
            ><input
              class="me-2"
              type="radio"
              name="order_type"
              value="short"
            />Short</label
          >
        </div>
        <h4>Leverage</h4>
        <div class="form-check form-check-inline d-flex justify-content-around">
          <label class="me-2"><input
              class="me-2"
              type="radio"
              name="leverage"
              value="2"
            />x2</label>
          <label class="me-2"><input
              class="me-2"
              type="radio"
              name="leverage"
              value="3"
            />x3</label>
          <label class="me-2"><input
              class="me-2"
              type="radio"
              name="leverage"
              value="4"
            />x4</label>
          <label class="me-2"><input
              class="me-2"
              type="radio"
              name="leverage"
              value="5"
            />x5</label>
        </div>

        <div class="input-group mt-3">
          <input
            type="number"
            step="0.01"
            class="form-control"
            placeholder="Volume"
            aria-label="Volume"
            aria-describedby="volume_addon"
            name="volume"
          />
          <span class="input-group-text" id="volume_addon"
            >{{amount_2.currency.symbol}}</span
          >
        </div>

        <div class="input-group mt-3">
          <input
            type="number"
            step="0.01"
            class="form-control"
            placeholder="Entry price"
            aria-label="Entry price"
            aria-describedby="entry_price_addon"
            name="entry_price"
          />
          <span class="input-group-text" id="entry_price_addon"
            >{{amount_2.currency.symbol}}</span
          >
        </div>

        <hr />

        <div class="input-group mt-3">
          <input
            type="number"
            step="0.01"
            class="form-control"
            placeholder="Take profit at"
            aria-label="Take profit at"
            aria-describedby="take_profit_addon"
            name="take_profit"
          />
          <span class="input-group-text" id="take_profit_addon"
            >{{amount_2.currency.symbol}}</span
          >
        </div>

        <div class="input-group mt-3">
          <input
            type="number"
            step="0.01"
            class="form-control"
            placeholder="Stop loss at"
            aria-label="Stop loss at"
            aria-describedby="stop_loss_addon"
            name="stop_loss"
          />
          <span class="input-group-text" id="stop_loss_addon"
            >{{amount_2.currency.symbol}}</span
          >
        </div>

        <div class="input-group mt-3 d-flex justify-content-between">
          <button class="btn btn-danger">Empty fields</button>
          <button class="btn btn-primary">Validate order</button>
        </div>
      </form>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <table class="table table-hover">
      <thead>
        <tr>
          <td>Order time</td>
          <td>Type</td>
          <td>Position opening time</td>
          <td>Position closed at</td>
          <td>Closing reason</td>
          <td>Volume</td>
          <td>Price</td>
          <td>Take profit</td>
          <td>Stop loss</td>
          <td>Profit / Loss</td>
          <td>Action</td>
        </tr>
      </thead>
      <tbody>
        {% for order in orders %}
        <tr>
          <td>{{ order.created_on}}</td>
          <td>{{ order.get_order_type_display}}</td>
          <td>{{ order.position_opened_at}}</td>
          <td>{{ order.position_closed_at}}</td>
          <td>{% if order.order_cancelled_at %}Cancelled{% elif order.stop_loss_reached %}Stop loss{% elif order.take_profit_reached %}Take profit{% else %}/{% endif %}</td>
          <td>{{order.volume}}</td>
          <td>{{order.entry_price}}</td>
          <td>{{order.take_profit}}</td>
          <td>{{order.stop_loss}}</td>
          <td>{{order.profit_loss}}</td>
          <td>{% if not order.order_cancelled_at and not order.position_closed_at %}<a href="{% url 'cancel_order' order.id %}" class="btn btn-warning">Cancel / Reduce</a>{% endif %}
            {% if not order.position_closed_at and order.position_opened_at and not order.order_cancelled_at %}<button class="btn btn-warning" onclick="openOrderEditModal({{order.id}}, {{order.entry_price}}, {{order.take_profit}}, {{order.stop_loss}}, true)">Change take profit or stop loss</button>{% endif %}
            {% if not order.position_opened_at and not order.order_cancelled_at %}<button class="btn btn-warning" onclick="openOrderEditModal({{order.id}}, {{order.entry_price}}, {{order.take_profit}}, {{order.stop_loss}}, false)">Edit order values</button>{% endif %}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table> 
  </div>
  <div id="editOrderModal" class="modal hide fade"">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Edit order</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">

            <label for="entry_price">Edit entry price</label>
            <div class="input-group mt-3">
            
              <input
                type="number"
                step="0.01"
                class="form-control"
                placeholder="Entry price"
                aria-label="Entry price"
                aria-describedby="entry_price_addon_edit"
                name="entry_price"
                id="updateEntryPrice"
              />
              <span class="input-group-text" id="entry_price_addon_edit"
                >{{amount_2.currency.symbol}}</span
              >
            </div>

            <label for="take_profit">Edit take profit</label>
            <div class="input-group mt-3">
            
              <input
                type="number"
                step="0.01"
                class="form-control"
                placeholder="Take profit at"
                aria-label="Take profit at"
                aria-describedby="take_profit_addon_edit"
                name="take_profit"
                id="updateTakeProfit"
              />
              <span class="input-group-text" id="take_profit_addon_edit"
                >{{amount_2.currency.symbol}}</span
              >
            </div>

            <label for="stop_loss">Edit stop loss</label>
            <div class="input-group mt-3">
            
              <input
                type="number"
                step="0.01"
                class="form-control"
                placeholder="Stop loss at"
                aria-label="Stop loss at"
                aria-describedby="stop_loss_addon_edit"
                name="stop_loss"
                id="updateStopLoss"
              />
              <span class="input-group-text" id="stop_loss_addon_edit"
                >{{amount_2.currency.symbol}}</span
              >
            </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <button type="button" onclick='updateOrder()' class="btn btn-primary">Save changes</button>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock body %}

{% block javascript %}
<script>

  let orderId = null;

  function openOrderEditModal(backOrderId, entryPrice, takeProfit, stopLoss, started){
    orderId = backOrderId;
    $('#updateEntryPrice').val(entryPrice);
    $('#updateEntryPrice').prop('disabled', started == true);
    $('#updateTakeProfit').val(takeProfit);
    $('#updateStopLoss').val(stopLoss);
    $('#editOrderModal').modal('show'); 
  }

  async function updateOrder(){
    
    
    
    const response = await fetch("{% url 'update_order' %}", {
      method: 'POST',
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json',
        'X-CSRFToken' : '{{ csrf_token }}'
      },
      body: JSON.stringify({
        id : orderId,
        entryPrice : $('#updateEntryPrice').val(),
        takeProfit : $('#updateTakeProfit').val(),
        stopLoss : $('#updateStopLoss').val()
        })
      });

      response.json().then(data => {
        console.log(data);
      });
  }

</script>

{% endblock javascript %}